# Generated by Django 4.0.1 on 2022-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_dog', '0002_owner_age_alter_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
