# Generated by Django 4.0.1 on 2022-01-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='actors',
        ),
        migrations.AlterModelTable(
            name='actor_movie',
            table='actors_movies',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
